{{- range $job := .Values.jobs }}
apiVersion: v1
data:
  MYSQL_USER: {{ $job.configs.secret_env.MYSQL_USER | b64enc }}
  MYSQL_PASSWORD: {{ $job.configs.secret_env.MYSQL_PASSWORD | b64enc }}
  MYSQL_PORT: {{ $job.configs.secret_env.MYSQL_PORT | b64enc | quote}}
  MYSQL_HOST: {{  $job.configs.secret_env.MYSQL_HOST | b64enc }}
  BUCKET_NAME: {{ $job.configs.secret_env.BUCKET_NAME | b64enc }}
  AWS_ACCESS_KEY_ID: {{ $job.configs.secret_env.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $job.configs.secret_env.AWS_SECRET_ACCESS_KEY | b64enc}}
  AWS_DEFAULT_REGION: {{ $job.configs.secret_env.AWS_DEFAULT_REGION | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: "{{ include "cronjobs.releaseName" $ }}-{{ $job.name }}-secret"
{{- end }}