# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


jobs:
- name: mysql2s3
  image:
    repository: pyaephyohein/mysql2s3bk
    tag: alpha
    imagePullPolicy: IfNotPresent
  schedule: "* * * * *"
  command: ["/bin/sh"]
  args:
  - "-c"
  - "/apps/src/backup.sh"
  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi
  failedJobsHistoryLimit: 1

  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  restartPolicy: OnFailure
  envFrom:
  - secretRef:
      name: <release-name>-mysql2s3-secret #update secret name
  configs:
    suspend:
      enabled: true
    secret_env:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql-password
      MYSQL_PORT: "3306" ## add quotes 
      MYSQL_HOST: localhost
      BUCKET_NAME: s3bucket
      AWS_ACCESS_KEY_ID: awsacessid
      AWS_SECRET_ACCESS_KEY: awsaccesskey
      AWS_DEFAULT_REGION: ap-southeast-1
