kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nginx-playground.fullname" . }}-data
  annotations:
    reloader.stakater.com/match: "true"
data:
  foo: |-
{{ .Values.files.foo | indent 4 }}